export const DISPLAY_POKEMON_SUCCESS = 'DISPLAY_POKEMON_SUCCESS';

export const DETAIL_POKEMON_SUCCESS = 'DETAIL_POKEMON_SUCCESS';

export const DETAIL_POKEMON_ERROR = 'DETAIL_POKEMON_ERROR';

export const SEARCH_POKEMON_SUCCESS = 'SEARCH_POKEMON_SUCCESS';

export const SEARCH_POKEMON_ERROR = 'SEARCH_POKEMON_ERROR';
